### ISSUE TITLE
Email Setup

### ISSUE THREAD

**Issue by kitarp29** [FFCSThingy/FFCSThingy2.0#100]
It would be really handy if the site Email setup and would notify users via Email.
I can work on it with Sendgrid and SMTP if given the right resources

**Comment by namsnath** [comment]
Could you elaborate? What would you like the users to be notified of?

**Comment by kitarp29** [comment]
When the Register or Change password.
Or any important event on the Website you want.
You can also set up way to make an automatic mailing system that can email all the registered users about any event/ update

**Comment by namsnath** [comment]
We just have a Google login, so I don't think this is required.
If we do add something that needs email alerts, we'll come back to this issue.
Thanks!
