### ISSUE TITLE
Fix no-async-promise-executor warnings in backend

### ISSUE THREAD

**Issue by namsnath** [FFCSThingy/FFCSThingy2.0#54]
### Functions Left:
**courseUtility.js:**

- updateHeatmap()
- doCleanRemovedCourses()
- doCleanRemovedCourses()

**Comment by 2bit-hack** [comment]
Can I work on this issue?

**Comment by namsnath** [comment]
@2bit-hack Sure!
I'll assign it to you.
You will have to remove this line so that ESLint picks up the errors. (Currently they show up as warnings)
https://github.com/FFCSThingy/FFCSThingy2.0/blob/11d62d54d0ddd6ac462b0b39efd3993399267c14/backend/.eslintrc.js#L30

You can run ESLint by using `npx eslint .` when in the `backend` folder.

**Comment by alexrobaina** [comment]
Hello! 
I think it is not necessary to remove 'no-async-promise-executor': 1
Because it's not necessary make two async and new promise, the first async can create several awaits.

**Comment by namsnath** [comment]
Yes, it's fine if you leave the ESLint file untouched. I'd prefer if you remove the line in question so that it shows up as an error in ESLint instead of a warning.

As for the actual fixes, running the ESLint command should point you to where the errors lie.

**Comment by namsnath** [comment]
https://eslint.org/docs/rules/no-async-promise-executor

This is the link to the actual ESLint error. 
Removing the `new Promise(...)` construct should ideally fix this error

**Comment by 2bit-hack** [comment]
Should I just remove `async` and `await` and chain the promises instead?

**Comment by namsnath** [comment]
I'd rather not do that, since those have a way of devolving into callback hell the next time it needs work. 

Leaving the basic structure of the code the same would be an ideal approach.

**Comment by 2bit-hack** [comment]
If I remove `new Promise(...)`, I'm left with an async function. In that case, I don't have to accept the `reject` and `resolve` functions, right? Should I just return `cleanDetails` or an error?

**Comment by namsnath** [comment]
Yup, that should work. 
We'll have to check that it still works and in the way it's intended. (Should, but no harm in checking)

**Comment by 2bit-hack** [comment]
I guess the code that calls these functions will also have to be changed, now that the function signatures are different

**Comment by namsnath** [comment]
The functions in question should be `doCleanRemovedCourses()` and `updateHeatmap()`.
Both of these are called using an `await`, so it shouldn't be an issue, since it would still return a promise.

Can test it out by doing a `console.log`.

**Comment by 2bit-hack** [comment]
Can confirm that they return promises

**Comment by namsnath** [comment]
Don't commit the package-lock please.
I need to update a few dependencies too, I'll handle that when I pull to master.

If you open a PR, please do so to the `dev` branch.

**Comment by namsnath** [comment]
Thanks @2bit-hack !

**Comment by 2bit-hack** [comment]
Thanks for having me!
