### ISSUE TITLE
Fix multiple Modal renders on initial Load

### ISSUE THREAD

**Issue by namsnath** [FFCSThingy/FFCSThingy2.0#62]
If showModal is true
Initial Render renders the modal with the animation multiple times

Possibly due to multiple re-renders of the navbar
Maybe move the modal to Dashboard?

**Comment by alexrobaina** [comment]
Hey @roerohan I can help with this issue. Do you thinks it's ok?
The problem is the modal or multiple re-renders of the navbar?

**Comment by namsnath** [comment]
Hey @alexrobaina, thanks for the interest!
On testing the current version right now, it seems the issue is no longer reproducible (by adding a basic modal to the Dashboard).
This is a very old issue, and the modal in question has been removed for a while, thus the issue staying open.

We have other issues you might like to try helping out with. I will be closing this.
If you could help find a case where modals added to Dashboard re-render/re-animate multiple times, that would be awesome as well. Thanks!
