### ISSUE TITLE
Add Screenshot/Save for timetable

### ISSUE THREAD

**Issue by namsnath** [FFCSThingy/FFCSThingy2.0#74]
There is no way to share/save timetables for now.

A useful feature would be to add a button that allows saving a screenshot of the timetable as a PNG/PDF or the course list as a CSV/TXT file.

Something like [this](https://www.npmjs.com/package/react-to-print) could be used, provided it keeps the CSS on print.

Exporting to a downloadable CSV/TXT file should be trivial.

**Comment by brij1999** [comment]
Hi @roerohan @namsnath I would like to work on this issue.

**Comment by namsnath** [comment]
Hey @brij1999 ,
Feel free to make a fork and a new branch for the feature. Something like "feat/timetable_screenshot". 
I'll assign this to you.

**Comment by namsnath** [comment]
Branch from dev, not master

**Comment by namsnath** [comment]
Thanks @brij1999 
Good work on the feature, works quite well!
