### ISSUE TITLE
Remove Date.now() calls from reducers

### ISSUE THREAD

**Issue by namsnath** [FFCSThingy/FFCSThingy2.0#92]
Lots of reducers call Date.now(). This is an anti-pattern and makes the reducer an impure function.

Solution
- Pass a timestamp with the dispatch
- Convert the timestamp to appropriate format inside the reducer

In terms of the implementation I had in mind, we could try passing a timestamp to the reducer (using `Date.now()`), which can then be processed to convert it to the ISOString that the reducer uses currently.
Essentially, the `Date.now()` component moves out of the reducers and to the place where the action is being dispatched. The reducers would not need any changes in logic.

Keep in mind, we will also have to modify the dispatches that happen from the components.

**Comment by dannyflatiron** [comment]
Hello I would like to tackle this issue could you assign it to me?

**Comment by namsnath** [comment]
Hey, let's work on one issue at a time for now. We can come back to this at a later time once #93 is resolved

**Comment by ays14** [comment]
Hi @namsnath 
The issue is marked open but there is no one assigned. I would like to take it up. Can you assign it to me?

**Comment by namsnath** [comment]
Hey @ays14 , thanks!
I can assign this to you.

In terms of the implementation I had in mind, you could try passing a timestamp to the reducer (using `Date.now()`), which can then be processed to convert it to the ISOString that the reducer uses currently.
Essentially, the `Date.now()` component moves out of the reducers and to the place where the action is being dispatched. The reducers would not need any changes in logic.

Keep in mind, you will also have to modify the dispatches that happen from the components.

**Comment by ays14** [comment]
> Hey @ays14 , thanks!
> I can assign this to you.
> 
> In terms of the implementation I had in mind, you could try passing a timestamp to the reducer (using `Date.now()`), which can then be processed to convert it to the ISOString that the reducer uses currently.
> Essentially, the `Date.now()` component moves out of the reducers and to the place where the action is being dispatched. The reducers would not need any changes in logic.
> 
> Keep in mind, you will also have to modify the dispatches that happen from the components.

Thanks for the info @namsnath. Will ping if I have any doubt.

**Comment by 16sweetyjain** [comment]
@namsnath  can i work on this issue?

**Comment by namsnath** [comment]
Hey,
I've currently assigned the issue to @ays14 .
If they are not working on it, I'd be happy to assign it to you. 
We'll wait for their reply.

**Comment by ays14** [comment]
I'm on it, will raise a PR tomo.

**Comment by namsnath** [comment]
Awesome

**Comment by ays14** [comment]
Hey @16sweetyjain , you may take this up. 
Hey @namsnath , unfortunately I am running macOS 11 Beta, which is why mongo is not supported and I am unable to test out the application. I apologise that I did not finish the task but I can not do anything about it.

**Comment by namsnath** [comment]
Alright. No issues.
@16sweetyjain would you like to take it up?

**Comment by namsnath** [comment]
Fixed syncTimetable in bcef0789d7db95b90e6c8e6ae2c4aac9c22c2f17
